### PR TITLE
feat: collapse nav on click

### LINKED ISSUE #27: Navbar Collapse
The navbar hamburger menu is not collapsing on a click

### PR DESCRIPTION
**Pull request by YasiOnFire**
Fixes #27

### CODE REVIEW

**Comment by thetarandhiman** [comment]
> 
> 
> Fixes #27

Thanks! Happy hacking!

**Comment by YasiOnFire** [comment]
@thetarandhiman any chance for a hacktoberfest-accepted label?

**Comment by thetarandhiman** [comment]
> 
> 
> @thetarandhiman any chance for a hacktoberfest-accepted label?

Yes, it is hacktoberfest-accepted!

**Comment by YasiOnFire** [comment]
You actually need to explicitly add the label to this PR for it to count :) As is stated in the rules section on https://hacktoberfest.digitalocean.com/

**Pull request merged**
